# Generated by Django 5.1.4 on 2024-12-16 09:02

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Rang',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='Должность')),
            ],
            options={
                'verbose_name': 'Должность',
                'verbose_name_plural': 'Должности',
                'db_table': 'rang',
            },
        ),
        migrations.CreateModel(
            name='Depart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, unique=True, verbose_name='Департамент')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='tabel.depart', verbose_name='Родитель')),
            ],
            options={
                'verbose_name': 'Департамент',
                'verbose_name_plural': 'Департаменты',
                'db_table': 'depart',
            },
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('tab', models.IntegerField(db_index=True, primary_key=True, serialize=False, unique=True, verbose_name='Табельный номер')),
                ('fio', models.CharField(max_length=250, verbose_name='ФИО')),
                ('adname', models.CharField(db_index=True, max_length=50, verbose_name='Фамилия и инициалы')),
                ('depart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tabel.depart', verbose_name='Департамент')),
            ],
            options={
                'verbose_name': 'Сотрудник',
                'verbose_name_plural': 'Сотрудники',
                'db_table': 'employee',
            },
        ),
        migrations.CreateModel(
            name='EmployeeAccounting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employment_date', models.DateField(default=datetime.date(2024, 12, 16), verbose_name='Дата приема')),
                ('dismissal_date', models.DateField(blank=True, null=True, verbose_name='Дата увольнения')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tabel.employee', verbose_name='Сотрудник')),
            ],
            options={
                'verbose_name': 'Учет сотрудника',
                'verbose_name_plural': 'Учет сотрудников',
                'db_table': 'employee_accounting',
            },
        ),
        migrations.CreateModel(
            name='Tabel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=datetime.date(2024, 12, 16), verbose_name='Дата')),
                ('type', models.CharField(max_length=6, verbose_name='Буквенное обозначение')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tabel.employee', verbose_name='Сотрудник')),
            ],
            options={
                'verbose_name': 'Табель',
                'verbose_name_plural': 'Табели',
                'db_table': 'tabel',
            },
        ),
        migrations.CreateModel(
            name='Vacation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField(default=datetime.date(2024, 12, 16), verbose_name='Дата начала')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='Дата окончания')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tabel.employee', verbose_name='Сотрудник')),
            ],
            options={
                'verbose_name': 'Учет отпуска',
                'verbose_name_plural': 'Учет отпусков',
                'db_table': 'vacation',
            },
        ),
    ]
