# Generated by Django 5.1.4 on 2024-12-17 11:07

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tabel', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeeaccounting',
            name='employment_date',
            field=models.DateField(default=datetime.date(2024, 12, 17), verbose_name='Дата приема'),
        ),
        migrations.AlterField(
            model_name='tabel',
            name='date',
            field=models.DateField(default=datetime.date(2024, 12, 17), verbose_name='Дата'),
        ),
        migrations.AlterField(
            model_name='vacation',
            name='start_date',
            field=models.DateField(default=datetime.date(2024, 12, 17), verbose_name='Дата начала'),
        ),
    ]
