# Generated by Django 5.1.4 on 2024-12-17 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tabel', '0003_alter_employeeaccounting_employment_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='rang',
            name='is_admin',
            field=models.BooleanField(default=False, verbose_name='Права админа'),
        ),
    ]
