# Generated by Django 5.1.4 on 2024-12-17 12:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tabel', '0004_rang_is_admin'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='rang',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='tabel.rang', verbose_name='Должность'),
            preserve_default=False,
        ),
    ]
